# Generated by Django 5.2.1 on 2025-09-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Percentage complete based on tasks'),
        ),
    ]
