# Generated by Django 5.2.4 on 2025-07-18 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #3B82F6)', max_length=7)),
                ('icon', models.CharField(default='light-bulb', help_text='Heroicon name (e.g., light-bulb, code, cog)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code (e.g., #6B7280)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(help_text='Brief description of what this prompt does')),
                ('content', models.TextField(help_text='The actual prompt text')),
                ('prompt_type', models.CharField(choices=[('text', 'Text Prompt'), ('code', 'Code Prompt'), ('creative', 'Creative Writing'), ('analysis', 'Analysis'), ('instruction', 'Instruction'), ('question', 'Question'), ('template', 'Template')], default='text', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=15)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Success rate percentage', max_digits=5)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('example_input', models.TextField(blank=True, help_text='Example input for the prompt', null=True)),
                ('example_output', models.TextField(blank=True, help_text='Example output from the prompt', null=True)),
                ('context_notes', models.TextField(blank=True, help_text='Additional context or instructions', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this prompt is visible to all users')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured prompts appear prominently')),
                ('is_template', models.BooleanField(default=False, help_text='Template prompts can be used as starting points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_prompts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='prompts.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='prompts', to='prompts.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_collections', to=settings.AUTH_USER_MODEL)),
                ('prompts', models.ManyToManyField(related_name='collections', to='prompts.prompt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(blank=True, null=True)),
                ('output_text', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('execution_time', models.DurationField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='prompts_pro_created_ef9f89_idx'), models.Index(fields=['prompt', 'user'], name='prompts_pro_prompt__101fc5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-created_at'], name='prompts_pro_created_d50e89_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['category'], name='prompts_pro_categor_80711f_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['prompt_type'], name='prompts_pro_prompt__7792e1_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['difficulty'], name='prompts_pro_difficu_e24bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['is_public'], name='prompts_pro_is_publ_db89cf_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['is_featured'], name='prompts_pro_is_feat_2fdf6a_idx'),
        ),
    ]
