# Generated by Django 5.2.4 on 2025-07-20 19:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=10)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('lastpass', 'LastPass'), ('bitwarden', 'Bitwarden'), ('1password', '1Password'), ('chrome', 'Chrome'), ('firefox', 'Firefox')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_successful', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PasswordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('icon', models.CharField(default='fa-folder', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('encrypted_password', models.TextField()),
                ('website_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('password_strength', models.CharField(choices=[('very_weak', 'Very Weak'), ('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong'), ('very_strong', 'Very Strong')], default='medium', max_length=12)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('requires_2fa', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='pwlockdown.passwordcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Entries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('admin', 'Admin')], default='view', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwlockdown.passwordentry')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_passwords_by', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_passwords_with', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('password_entry', 'shared_with')},
            },
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_passwords', through='pwlockdown.PasswordShare', through_fields=('password_entry', 'shared_with'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_created', 'Password Created'), ('password_updated', 'Password Updated'), ('password_deleted', 'Password Deleted'), ('password_viewed', 'Password Viewed'), ('password_shared', 'Password Shared'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('failed_login', 'Failed Login'), ('password_exported', 'Password Exported'), ('settings_changed', 'Settings Changed')], max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, max_length=100)),
                ('backup_codes', models.JSONField(blank=True, default=list)),
                ('default_password_length', models.IntegerField(default=16)),
                ('include_uppercase', models.BooleanField(default=True)),
                ('include_lowercase', models.BooleanField(default=True)),
                ('include_numbers', models.BooleanField(default=True)),
                ('include_symbols', models.BooleanField(default=True)),
                ('exclude_ambiguous', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=1800)),
                ('auto_lock_enabled', models.BooleanField(default=True)),
                ('password_expiry_notifications', models.BooleanField(default=True)),
                ('weak_password_alerts', models.BooleanField(default=True)),
                ('login_notifications', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('items_per_page', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwlockdown_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='pwlockdown.passwordfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'parent', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PasswordGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField(default=16, validators=[django.core.validators.MinLengthValidator(8)])),
                ('include_uppercase', models.BooleanField(default=True)),
                ('include_lowercase', models.BooleanField(default=True)),
                ('include_numbers', models.BooleanField(default=True)),
                ('include_symbols', models.BooleanField(default=True)),
                ('exclude_ambiguous', models.BooleanField(default=True)),
                ('custom_symbols', models.CharField(blank=True, max_length=100)),
                ('exclude_chars', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
    ]
