# Generated by Django 5.2.4 on 2025-08-14 10:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIKERT', 'Likert Scale'), ('MULTI', 'Multiple Choice'), ('SINGLE', 'Single Choice'), ('MATRIX', 'Matrix Question'), ('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('NPS', 'Net Promoter Score'), ('RANK', 'Ranking'), ('DATE', 'Date'), ('NUMBER', 'Number')], max_length=20)),
                ('prompt', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('options_json', models.JSONField(blank=True, default=dict)),
                ('scale_min', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('scale_max', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10)])),
                ('order', models.IntegerField(default=0)),
                ('logic_json', models.JSONField(blank=True, default=dict)),
                ('anonymity_mode', models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('ESCROW', 'Private (Escrow)'), ('SIGNED', 'Signed')], default='ESCROW', max_length=20)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.section')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('section', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publish_start', models.DateTimeField()),
                ('publish_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('k_threshold', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('cohort_json', models.JSONField(blank=True, default=dict)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('identity_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'identity_user')},
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('aggregates_json', models.JSONField(default=dict)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='surveys.survey')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='surveys.survey')),
            ],
            options={
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('is_signed', models.BooleanField(default=False)),
                ('followup_opt_in', models.BooleanField(default=False)),
                ('preferred_contact', models.TextField(blank=True)),
                ('moderation_status', models.CharField(choices=[('OK', 'OK'), ('FLAGGED', 'Flagged for Review'), ('REDACTED', 'Redacted')], default='OK', max_length=20)),
                ('flags_json', models.JSONField(blank=True, default=dict)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.response')),
            ],
            options={
                'unique_together': {('response', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('survey', 'order')},
        ),
    ]
