# Generated by Django 5.2.1 on 2025-08-14 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('316', '316 Stainless Steel'), ('304', '304 Stainless Steel'), ('AL6XN', 'AL6XN Alloy'), ('RM', 'RM Material'), ('GP', 'GP Material'), ('BM', 'BM Material'), ('TE', 'TE Material'), ('FM', 'FM Material'), ('HW', 'Hot Water'), ('TW', 'Tepid Water'), ('CW', 'Cold Water'), ('CMF', 'CMF Material'), ('RO', 'RO Material'), ('WW', 'WW Material')], max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BOMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_bom.equipmenttype')),
            ],
            options={
                'ordering': ['template_code'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='in_progress', max_length=50)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_bom.equipmenttype')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('customer', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planning', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('Item', 'Item'), ('Sub Assy', 'Sub Assembly'), ('FG FAB', 'Finished Goods Fabrication')], max_length=100)),
                ('supply_type', models.CharField(blank=True, choices=[('Pegged Supply', 'Pegged Supply'), ('Phantom', 'Phantom'), ('Item', 'Item')], max_length=100)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_train_size', models.CharField(blank=True, max_length=50)),
                ('gas_train_mount', models.CharField(blank=True, max_length=50)),
                ('heater_model', models.CharField(blank=True, max_length=50)),
                ('flange_inlet', models.CharField(blank=True, max_length=50)),
                ('stack_diameter', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('CENTER', 'Center')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_production', 'In Production'), ('completed', 'Completed'), ('shipped', 'Shipped')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_bom.bomtemplate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_bom.equipmenttype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='equipment_bom.job')),
                ('primary_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_equipment', to='equipment_bom.material')),
                ('secondary_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_equipment', to='equipment_bom.material')),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('Item', 'Item'), ('Sub Assy', 'Sub Assembly'), ('Phantom', 'Phantom')], max_length=100)),
                ('supply_type', models.CharField(blank=True, choices=[('Pegged Supply', 'Pegged Supply'), ('Phantom', 'Phantom'), ('Item', 'Item')], max_length=100)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('CENTER', 'Center')], max_length=50)),
                ('gas_train_size', models.CharField(blank=True, max_length=50)),
                ('gas_train_mount', models.CharField(blank=True, max_length=50)),
                ('heater_model', models.CharField(blank=True, max_length=50)),
                ('flange_inlet', models.CharField(blank=True, max_length=50)),
                ('stack_diameter', models.CharField(blank=True, max_length=50)),
                ('tank_diameter', models.CharField(blank=True, max_length=50)),
                ('tank_height', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_production', 'In Production'), ('completed', 'Completed')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_bom.bomtemplate')),
                ('equipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='equipment_bom.equipmentitem')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_bom.material')),
            ],
            options={
                'ordering': ['component_number'],
                'unique_together': {('equipment_item', 'component_number')},
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_type', models.CharField(choices=[('Heater Diameter', 'Heater Diameter'), ('Heater Height', 'Heater Height'), ('Stack Diameter', 'Stack Diameter'), ('Flange Inlet', 'Flange Inlet'), ('Gas Train Size', 'Gas Train Size'), ('Gas Train Mount', 'Gas Train Mount'), ('Heater Model', 'Heater Model'), ('Tank Diameter', 'Tank Diameter'), ('Tank Height', 'Tank Height'), ('Material', 'Material'), ('Type', 'Type'), ('HP', 'Horsepower')], max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='equipment_bom.bomcomponent')),
                ('equipment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='equipment_bom.equipmentitem')),
            ],
            options={
                'ordering': ['spec_type'],
            },
        ),
    ]
