# Generated by Django 5.2.1 on 2025-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='economizer_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='flow_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='head',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='heater_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='inlet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='outlet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='pressure_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='pump_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='tank_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='working_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
