# Generated by Django 5.2.4 on 2025-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('lyrics', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('styles', models.JSONField(default=list, help_text="List of styles, e.g., ['disco', 'rap', 'cinematic']")),
                ('excluded_styles', models.JSONField(blank=True, default=list)),
                ('weirdness', models.PositiveSmallIntegerField(default=50, help_text='0–100')),
                ('style_influence', models.PositiveSmallIntegerField(default=50, help_text='0–100')),
                ('is_instrumental', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
